name: Tests
on: 
  - pull_request
  - push
jobs:
  build-and-run-tests:
    name: Build & run tests
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'
    - name: Build
      run: go build ./...
    - name: Run go vet
      run: go vet ./...
    - name: Run go fmt
      run: |
        out="$(go fmt ./...)"
        if [[ -n "${out}" ]]; then
          echo "Need to run `go fmt` on:"
          echo "${out}"
          exit 1
        fi
    - name: Run go tests
      run: go test -v ./...
    - name: Run go tests (-race)
      run: go test -race -v ./...
    - name: Build test docker image
      run: |
        touch version.sh
        docker build -t c2fmzq/tlsproxy:test .
        docker run --rm --interactive c2fmzq/tlsproxy:test -v
